---
# vars file for 600-test-role/

# When true the role will runs tasks to use OSPD to generate a container list.
# When false the provided totaltaglist in the files/ directroy will be used
   
gather_list: false

registry:
  container_registry: registry.access.redhat.com
  container_project: rhosp13
  destination_registry: example.com

provisioning_network: 192.168.24.0/24

# Undercloud environment variables used for running openstack commands on the undercloud using shell module
# Not necessary if {{ gather_list }} is set to false

undercloud_admin_password: ChangeMe

undercloud_auth_env_v2:
  NOVA_VERSION: 1.1
  OS_PASSWORD: "{{ undercloud_admin_password }}"
  OS_AUTH_URL: "https://ospd-host.example.com:13000/v2.0"
  OS_USERNAME: admin
  OS_TENANT_NAME: admin
  COMPUTE_API_VERSION: 1.1
  OS_BAREMETAL_API_VERSION: 1.15
  OS_NO_CACHE: True
  OS_CLOUDNAME: undercloud
  OS_IMAGE_API_VERSION: 1


undercloud_auth_env_v3:
  NOVA_VERSION: 1.1
  OS_PASSWORD: "{{ undercloud_admin_password }}"
  OS_AUTH_URL: "https://ospd-host.example.com:13000/v3"
  OS_USERNAME: admin
  OS_AUTH_TYPE: password
  OS_PROJECT_NAME: admin
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_DOMAIN_NAME: Default
  COMPUTE_API_VERSION: 1.1
  OS_BAREMETAL_API_VERSION: 1.34
  OS_NO_CACHE: True
  OS_CLOUDNAME: undercloud
  OS_IDENTITY_API_VERSION: 3


# Openstack Platofrm Z Release Dates 

z_release: "{{ Z4 }}"

GA:
  release: "2018-06-27"
  async: "2018-07-19"
  label: "GA"
Z1:
  release: "2018-07-19"
  async: "2018-08-29"
  label: "Z1"  
Z2:
  release: "2018-08-29"
  async: "2018-11-13"
  label: "Z2"
Z3:
  release: "2018-11-13"
  async: "2019-01-16"
  label: "Z3"  
Z4:
  release: "2019-01-16"
  async: "2019-03-13"
  label: "Z4"  
Z5: 
  release: "2019-03-13"
  async: "2019-04-30"
  label: "Z5"
Z6: 
  release: "2019-04-30"
  async: "2019-07-10"
  label: "Z6"
Z7: 
  release: "2019-07-10"
  async: "2019-09-04"
  label: "Z7"  
Z8: 
  release: "2019-09-04"
  async: "2019-11-06"
  label: "Z8"
Z9:
  release: "2019-11-06"
  async: "2020-02-01"
  label: "Z9"
