---

# The vars section creates variables for each image using the json data aquired from skopeo inspects in {{ inspected.results }}  
# Jinja 'if' statements in the variable declarations are used to work around a blank entry causing the loop to fail.

# Due to the limitations of datetime manipulation in Ansible strings had top be converted to datetime objects and then converted
# to an integer representing epoch seconds.

# The shell module runs a skopeo command instead of using the podman_container_facts or docker_container_facts Ansible modules.
# This is because according ot the module man pages "If an image does not exist locally, it will not appear in the results."
# We want to inspect then tag a bunch of remote container images before having to pull them so skopeo is used via shell module.

- name: Tag Z Release Images
  vars:
    ImageName: "{% if item.stdout|length %}{{ item.stdout | from_json | json_query('[ Labels.name ]') }}{% endif %}"
    ImageFullName: "{% if item.stdout|length %}{{ item._ansible_item_label }}{% endif %}"
    ImageCreated: "{% if item.stdout|length %}{{ item.stdout | from_json | json_query('[ Created ]') }}{% endif %}"
    ImageBatch: "{% if item.stdout|length %}{{ item.stdout | from_json | json_query('[ Labels.batch ]') }}{% endif %}"
    ImageBuildDate: "{% if item.stdout|length %}{{ item.stdout | from_json | json_query('[ `Labels.build-date` ]') }}{% endif %}"
    ImageCreatedDate: "{% if ImageCreated|length %}{% for timestamp in ImageCreated %}{{ timestamp.split('T')[0]}}{% endfor %}{% endif %}"
    ImageCreatedEpoch: "{% if ImageCreatedDate|length %}{{ (ImageCreatedDate|to_datetime(format='%Y-%m-%d')).strftime('%s')|int }}{% endif %}"
    ZReleaseEpoch: "{{ (z_release.release|to_datetime(format='%Y-%m-%d')).strftime('%s')|int }}"
    ZReleaseEpochPlus7Days: "{{ ((ZReleaseEpoch | int) + ( 86400 * 7 )) }}"
    ZReleaseEpochMinus20Days: "{{ ((ZReleaseEpoch| int) - ( 86400 * 20 )) }}"
  shell: >
    skopeo copy 
    docker://{{ ImageFullName }}  
    docker://{{ registry.destination_registry }}/{{ ImageName[0] }}:{{ z_release.label }}
  with_items: "{{ inspected.results }}"
  when:  ImageCreatedEpoch >= ZReleaseEpochMinus20Days and ImageCreatedEpoch <= ZReleaseEpochPlus7Days

